### ISSUE TITLE
Implement Account-specific controls

### ISSUE THREAD

**Issue by MikeDev101** [meower-media-co/Meower-Server#10]
^

This feature will allow the user to view all account activity such as last login timestamp, last known IP address, and account creation timestamps.

This will also permit the user to provide an email to open up the possibility for an account recovery system as well as email-based notifications. More ideas suggested for this.

This should also implement an account deletion feature, as mentioned in https://github.com/meower-media-co/Meower/issues/96

Also, a much needed feature is the ability to change/reset account passwords, as mentioned in https://github.com/meower-media-co/Meower/issues/49

**Comment by tnix100** [comment]
Update on this after 3 and half months:

I've added account deletions in the Mongo patch, and have started work on a data export feature. Still unsure how we're going to securely store email addresses for account recovery though.

![image](https://user-images.githubusercontent.com/61485190/164969152-0890ce04-ef88-403d-be4c-c7fc05b603d8.png)
![image](https://user-images.githubusercontent.com/61485190/164969156-f4f36034-b53b-4836-bd76-9ddff8fcd278.png)
![image](https://user-images.githubusercontent.com/61485190/164969166-d0c29916-5eb2-4fec-a236-99de77105ac4.png)
![image](https://user-images.githubusercontent.com/61485190/164969168-9eab4b21-cc43-4994-aa45-654139d48d53.png)

**Comment by MikeDev101** [comment]
Should be implemented as of b5r7
