### ISSUE TITLE
The whitelist issue

### ISSUE THREAD

**Issue by showierdata9978** [meower-media-co/Meower-Server#113]
mashedpotatos

**Comment by showierdata9978** [comment]
(list of all words that need to be added to the whitelist for containing profanity)

**Comment by theotherhades** [comment]
i feel like it would be better to keep a blacklist system but just not use bpf's one. maybe write our own into the server or something?

**Comment by showierdata9978** [comment]
> i feel like it would be better to keep a blacklist system but just not use bpf's one. maybe write our own into the server or something?

its words that contain profanity lmao, (like mashedpotatos, or just potatos)

**Comment by showierdata9978** [comment]
> Member

fixed that word

**Comment by mdwalters** [comment]
> > Member
> 
> fixed that word

meower member rip

**Comment by mdwalters** [comment]
analytics

**Comment by showierdata9978** [comment]
> analytics
Added to the PR
