### ISSUE TITLE
Implement direct messages

### ISSUE THREAD

**Issue by JoshAtticus** [meower-media-co/Meower-Server#116]
Please, we need this

**Comment by MikeDev101** [comment]
As of the current server, making a DM is simply creating a chat and inviting only a single user to it. Granted, this is a lazy workaround, but otherwise, a proper implementation of DMs would be useful in 0.6.0.

**Comment by MikeDev101** [comment]
Rewrite implements functionality (last time I checked. Closing for now, but @tnix100 feel free to re-open if otherwise).
