### ISSUE TITLE
Add feature that prevents fakes from coming on Meower

### ISSUE THREAD

**Issue by mdwalters** [meower-media-co/Meower-Server#118]
If the feature detects a username that already exists with a `I`, and the fake includes `l`, the server can return `Account exists`.

**Comment by theotherhades** [comment]
idk if this is necessary tbh

**Comment by mdwalters** [comment]
anti-furry

**Comment by theotherhades** [comment]
Verified badges will pretty much do this anyway, for example you'd know the user `@reald0n4ldtrumP` isn't the real one because the real donald trump account (`@realDonaldTrump`) would have a verified checkmark. This system works perfectly fine for other platforms so I don't see why it won't for Meower.

**Comment by mdwalters** [comment]
why are we referencing donald trump?

**Comment by Bloctans** [comment]
> Verified badges will pretty much do this anyway, for example you'd know the user `@reald0n4ldtrumP` isn't the real one because the real donald trump account (`@realDonaldTrump`) would have a verified checkmark. This system works perfectly fine for other platforms so I don't see why it won't for Meower.

#AgedLikeMilk

**Comment by JoshAtticus** [comment]
> > Verified badges will pretty much do this anyway, for example you'd know the user `@reald0n4ldtrumP` isn't the real one because the real donald trump account (`@realDonaldTrump`) would have a verified checkmark. This system works perfectly fine for other platforms so I don't see why it won't for Meower.
> 
> #AgedLikeMilk

#TwitterBlueMoment

**Comment by CST1229** [comment]
> > > Verified badges will pretty much do this anyway, for example you'd know the user `@reald0n4ldtrumP` isn't the real one because the real donald trump account (`@realDonaldTrump`) would have a verified checkmark. This system works perfectly fine for other platforms so I don't see why it won't for Meower.
> > 
> > 
> > #AgedLikeMilk
> 
> #TwitterBlueMoment

elon moment

**Comment by MikeDev101** [comment]
Meower CL4's account verification feature will rectify this issue. Closing.
