### ISSUE TITLE
[cl4] Documentation for the API

### ISSUE THREAD

**Issue by theotherhades** [meower-media-co/Meower-Server#119]
Currently at https://api.meower.org/ there is a placeholder but this page could be used for basic documentation, similar to that in the README but perhaps with more detail and examples. Alternatively the documentation could have its own `/docs` route. Thoughts?

**Comment by MikeDev101** [comment]
Re-prioritizing issue as high. Please make any documentation PRs to the main-cl4-branch.

**Comment by showierdata9978** [comment]
See: https://www.postman.com/showierdata9978/workspace/meower-cl4

**Comment by MikeDev101** [comment]
Similar to #154. Closing and continuing discussion in #154.
