### ISSUE TITLE
Server sometimes stringifies JSON in packets despite the client type not being `scratch`

### ISSUE THREAD

**Issue by CST1229** [meower-media-co/Meower-Server#122]
see the title

**Comment by Bloctans** [comment]
add a fixed svelte label?

**Comment by MikeDev101** [comment]
CL3-related bug. Not going to fix in this codebase as it will be rectified in the CL4 port.

**Comment by MikeDev101** [comment]
Closing since gone stale / won't fix. Legacy code issue appears to be too insignificant to patch from server-side, and it appears to be already patched client-side.
