### ISSUE TITLE
Server just died?

### ISSUE THREAD

**Issue by showierdata9978** [meower-media-co/Meower-Server#126]
@MikeDev101 @tnix100

**Comment by tnix100** [comment]
Yup

![Screenshot_2022-11-30-10-06-18-93_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://user-images.githubusercontent.com/61485190/204647621-8707cde5-53e7-4d6b-8d99-06a3e10ede41.jpg)

**Comment by tnix100** [comment]
Not for me

![Screenshot_2022-11-30-10-07-31-91_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://user-images.githubusercontent.com/61485190/204647814-d19f52a6-3af9-4fda-9d61-f4af4d6ef345.jpg)

**Comment by showierdata9978** [comment]
**6 hours ago lmao, from looking at the forms, the server did die

**Comment by tnix100** [comment]
Oh, I only just got the email and it said 3 mins ago

**Comment by showierdata9978** [comment]
> Oh, I only just got the email and it said 3 mins ago

lmao
