### ISSUE TITLE
Bots - Specify Client type (ex: Meowerbot, Svelte, Custom client, etc.)

### ISSUE THREAD

**Issue by Bloctans** [meower-media-co/Meower-Server#131]
(from MB docs)
Specify the client headers. If a library is misbehaving, this will help us handle the issues that may cause by temporarily blacklisting the client versions.

(make this a required step in the process of connecting to the server.)

**Comment by Bloctans** [comment]
like?

**Comment by showierdata9978** [comment]
mb versions <=1.4

**Comment by Bloctans** [comment]
> mb versions <=1.4

why? i cant even use the ctx mode in mb 2.1 because of long login times, <1.4 is all that works for me without being unstable

**Comment by showierdata9978** [comment]
no, 1.4 is before 1.5.x and thats the latest stable v1

**Comment by JoshAtticus** [comment]
I actually suggested this too, although I also said you should show what client a post was made from client side.

**Comment by MikeDev101** [comment]
Closing due to gone stale / Code is already present in CL4 branch, however documentation YTBD (Yet to be done).

**Comment by CST1229** [comment]
> Closing due to gone stale / Code is already present in CL4 branch, however documentation YTBD (Yet to be done).

This would probably qualify as completed then.
