### ISSUE TITLE
Trust key listener doesnt work sometimes

### ISSUE THREAD

**Issue by Bloctans** [meower-media-co/Meower-Server#134]
Whenever i assign a listener to the trust key, it wont respond with the listener once the server gets the msg sometimes

idk if its reproducable, but it needs to be fixed

**Comment by showierdata9978** [comment]
actually wait this may be why MB fails to login for you

**Comment by Bloctans** [comment]
> actually wait this may be why MB fails to login for you

it is.

**Comment by showierdata9978** [comment]
fixing with this client side patch
![image](https://user-images.githubusercontent.com/68120127/206890868-6317131e-306f-4f9b-a173-dff831867f2b.png)

**Comment by MikeDev101** [comment]
Use a client-side workaround FTTB, this issue will rectify itself with the CL4 port.
