### ISSUE TITLE
Loading page # >1 shows the first page

### ISSUE THREAD

**Issue by Bloctans** [meower-media-co/Meower-Server#135]
to repro (n svelte):
1. have an account with lots of gcs in
2. click load more

**Comment by MikeDev101** [comment]
Should be fixed with the release of the CL4 port. De-prioritizing issue.

**Comment by Bloctans** [comment]
> Should be fixed with the release of the CL4 port. De-prioritizing issue.

tnix said he will be making a fix for this because its annoying.

**Comment by Bloctans** [comment]
https://github.com/meower-media-co/Meower-Server/commit/9d522863ca5163793a1573152a74ba0da4e7b3e9

deploy this i guess
