### ISSUE TITLE
Reject scratch json packets

### ISSUE THREAD

**Issue by JoshAtticus** [meower-media-co/Meower-Server#138]
Pretty self explanatory to anyone who has had their client glitch out from scratch json packets. This would essentially send an error code when someone attempts to send a scratch json packet, and simply reject it. (e.g. "E:023 | Scratch packet rejected" or "E:023 | Packet rejected".)

**Comment by showierdata9978** [comment]
there is a rejected status alr :)

**Comment by JoshAtticus** [comment]
Oh ok

**Comment by CST1229** [comment]
Alternatively, we could just fix Scratch JSON packets (so that they don't get stringified for other clients).

**Comment by JoshAtticus** [comment]
> Alternatively, we could just fix Scratch JSON packets (so that they don't get stringified for other clients).

Except scratch is now deprecated anyways, and banning them would stop roblox coming back through bots.

**Comment by mdwalters** [comment]
#NOMORESCRATCHBOTS

**Comment by MikeDev101** [comment]
This is a bug within CL3, and will not be addressed. This issue will be fixed in the CL4 port.

**Comment by zzthebooplister** [comment]
> #NOMORESCRATCHBOTS

no thanks

**Comment by showierdata9978** [comment]
cl4 port is essentially cancelled from what iv seen

**Comment by tnix100** [comment]
Closing as this still doesn't need any action. Scratch clients work fine and don't break stuff anymore.
