### ISSUE TITLE
Show you what reports were taken action on/declined

### ISSUE THREAD

**Issue by JoshAtticus** [meower-media-co/Meower-Server#144]
Recieving
> Sadly, we could not take action on one of your recent reports. The content you reported was not severe enough to warrant action being taken. We still want to thank you for your help with keeping Meower a safe and welcoming place!

is one thing, but not even knowing what on earth that report was is another thing, and quite annoying too.  Same goes for

> We took action on one of your recent reports. Thank you for your help with keeping Meower a safe and welcoming place!

What recent report was taken action on???

Instead, Meower should send the messages containing the message and/or user that had their content/account taken action on.
Examples:
> Sadly, we could not take action on one of your recent reports. The content you reported was not severe enough to warrant action being taken. We still want to thank you for your help with keeping Meower a safe and welcoming place! 
>
> Content reported: Welcome to Meower! We welcome you with open arms! You can get started by making friends in the global chat or home, or by searching for people and adding them to a group chat. We hope you have fun! (Inbox Message)

> Sadly, we could not take action on one of your recent reports. The content you reported was not severe enough to warrant action being taken. We still want to thank you for your help with keeping Meower a safe and welcoming place! 
>
> User reported: @joshtheverynicenormaluser

> We took action on one of your recent reports. Thank you for your help with keeping Meower a safe and welcoming place!
>
> Content reported: am evil hacker ban me or will destroy meower (Posted by @definitelynotjoshtheveryevilhacker)

> We took action on one of your recent reports. Thank you for your help with keeping Meower a safe and welcoming place!
>
> User reported: @definitelynotjoshtheveryevilhacker

**Comment by tnix100** [comment]
That would give too much info imo, could lead to harassment of people who had content taken down/were banned.

**Comment by JoshAtticus** [comment]
> That would give too much info imo, could lead to harassment of people who had content taken down/were banned.

Well if they don't want to have their posts sent to the inbox of anyone who reported them, then they won't break the rules.

**Comment by JoshAtticus** [comment]
Plus users and posts are already public

**Comment by MikeDev101** [comment]
Closing since gone stale. Re-open if there are new ideas or contributions.
