### ISSUE TITLE
[cl4] dotenv does not work on windows

### ISSUE THREAD

**Issue by showierdata9978** [meower-media-co/Meower-Server#148]
Use a conf.py file with the contents

```py
from dotenv import dotenv_values
from os import enviorn as os_env

environ = {
  **dotenv_values(".env")
  **os_env
  }
  
def getenv(key: str, default=None) -> str:
       return  environ.get(key, default)
 ```
 and import that instead

**Comment by showierdata9978** [comment]
(this is needed to changed mongo and redis URIS)

**Comment by tnix100** [comment]
huh?
It works fine for me on Windows. I've been developing the whole CL4 port on Windows and haven't had any problems.

**Comment by showierdata9978** [comment]
Dotenv does not work on windows 10 (home), because it modifies os 
Environ

**Comment by MikeDev101** [comment]
Are you sure you used `py -m pip install -r requirements.txt`?

**Comment by tnix100** [comment]
> Dotenv does not work on windows 10 (home), because it modifies os Environ

Do you get an error when trying to start the server or do the values just not get set?

**Comment by showierdata9978** [comment]
just do not get set

**Comment by tnix100** [comment]
> just do not get set

Hm, alright, I will try Windows 10 Home and see if I can reproduce this.

**Comment by tnix100** [comment]
What Python version are you using?

**Comment by showierdata9978** [comment]
3.10.x im not actually at home RN

**Comment by tnix100** [comment]
Were you using Windows ARM on your rpi or were you on an x86 computer?

**Comment by showierdata9978** [comment]
x86 based  intel

**Comment by MikeDev101** [comment]
Which variant of x86? The 32-bit version (x86) or 64-bit (x86_64)? it's likely you are actually using x86_64.
Regardless, a possible solution is to upgrade to Python 3.11 or newer.

**Comment by tnix100** [comment]
> Which variant of x86? The 32-bit version (x86) or 64-bit (x86_64)? it's likely you are actually using x86_64. Regardless, a possible solution is to upgrade to Python 3.11 or newer.

I use Python 3.10.8 (64-bit) without any problem.

I'm also getting a test VM ready to see if I can reproduce this.
![image](https://user-images.githubusercontent.com/61485190/216713889-1c032ae4-ca07-487a-8fbb-634a500c9612.png)

**Comment by showierdata9978** [comment]
x86_64 def

**Comment by MikeDev101** [comment]
Python 3.11.0 on Windows 10 Education Edition (Work PC) works. I don't have any issues with dotenv.

**Comment by tnix100** [comment]
> Python 3.11.0 on Windows 10 Education Edition (Work PC) works. I don't have any issues with dotenv.

Windows Education is very similar to Pro/Enterprise (Pro is what I use), Windows Home has some interesting restrictions that may be causing something weird.

**Comment by tnix100** [comment]
. . .
![image](https://user-images.githubusercontent.com/61485190/216714587-dd11e948-08c7-4d45-ac73-452c45e4d036.png)

**Comment by showierdata9978** [comment]
uh what?

**Comment by tnix100** [comment]
This should be fixed now
