### ISSUE TITLE
Refactor Code + Use a database instead of JSON?

### ISSUE THREAD

**Issue by Chiroyce1** [meower-media-co/Meower-Server#15]
IMO putting everything in one file makes it crammed, why not separate parts of the backend into separate files and call them from the `main.py` file? It improves readability and doesn't cause any harm to the functionality.. 

And using JSON for storing data is fine, but in my experience, it has caused **significant** overhead with large files. A database system should get rid of writing to multiple files manually (especially if you have multiple files open in the program at once), and decrease read/write times. `sqlite` may be a good idea, it's comes as a default Python library.

I know that this will take quite a lot of time to implement, I may be able to help.
Please do consider this, thanks!

**Comment by MikeDev101** [comment]
1. I have been considering refactoring the code for a while now. It's a pain but I don't mind. It's just not a high enough priority yet.
2. A proper database system has been on my radar as well, but again, not a high enough priority.

**Comment by wgyt** [comment]
@MikeDev101 we could use mongodb to do this

**Comment by MikeDev101** [comment]
Because of development complications code refactoring has started.

**Comment by Chiroyce1** [comment]
Is development still going to continue outside of Scratch?

**Comment by MikeDev101** [comment]
Yes. We will continue development, no longer under the control of the
Scratch Team.

**Comment by MikeDev101** [comment]
Forgot to mention: Code refactoring has been completed.
