### ISSUE TITLE
[cl4 | latest] /docs does not have correct information 

### ISSUE THREAD

**Issue by showierdata9978** [meower-media-co/Meower-Server#154]
**Describe the bug**
/docs does not have correct information (OPENAPI AutoDoc SPEC)
**To Reproduce**
1. Go to /docs
2. Scroll down to any point that requires auth or json

**Expected behavior**?
No examples or auth status is shown

**Comment by MikeDev101** [comment]
Lowering priority level. API documentation in the README is a higher priority at this time.

**Comment by tnix100** [comment]
> **Describe the bug** /docs does not have correct information (OPENAPI AutoDoc SPEC) **To Reproduce** Steps to reproduce the behavior:
> 
>     1. Go to /docs
> 
>     2. Scroll down to any point that requires auth or json
> 
> 
> **Expected behavior**? No examples or auth status is shown

I didn't even realize OpenAPI docs were enabled, so as Mike said, not a high priority right now.

**Comment by MikeDev101** [comment]
Suggestion: Disable the /docs endpoint https://testdriven.io/tips/80107066-795c-4026-b7df-e250cdcd3dac/

**Comment by tnix100** [comment]
Should just disable /docs and make our own documentation. I will get started on making docs soon.

**Comment by tnix100** [comment]
Closing as this was only a feature of CL4 and CL4 is no longer planned.
