### ISSUE TITLE
[cl4 | https://github.com/meower-media-co/Meower-Server/commit/d69dfe42a4f4532ff8dd783214e817195052faca ] Summary

### ISSUE THREAD

**Issue by showierdata9978** [meower-media-co/Meower-Server#156]
## Current behavior
Unable to start cl4 server, via `python3 run_cl4.py`

## Screenshots / Logs

![image](https://user-images.githubusercontent.com/68120127/218913430-d30ffde9-1adb-4b7b-bfc6-34ba3f8080d8.png)

## Platform info

**Meower Server**
- Python: 3.10
- MongoDB: 6.2.0
- Redis: Redis for windows
- Meower Server Version + Build Date: https://github.com/meower-media-co/Meower-Server/commit/d69dfe42a4f4532ff8dd783214e817195052faca | 17 hours ago

**Desktop/Server**
 - OS:  Windows
 - Version: 10 Home
 - RAM:  8GB
 - Storage: 1TB
 - CPU Architecture: x86_64
 
## Did I read the instructions before making this bug report?

**I have read the instructions.**

**Comment by tnix100** [comment]
Fixed as of [03c3e28](https://github.com/meower-media-co/Meower-Server/commit/03c3e2828058e9b95180e9cbf361a982c6f282ac).
