### ISSUE TITLE
[cl4] 🤖 Create a bot session when the bot is created

### ISSUE THREAD

**Issue by showierdata9978** [meower-media-co/Meower-Server#157]
^
## alternatives
send an extra 2 requests on bot creation, to just create, and start a bot (assuming the bot has alr been coded)
 
**Additional context**
Annoying to copy paste/ run extra requests right now with postman as a clweb client

**Comment by tnix100** [comment]
This will only require 1 request in total in the next commit :)

**Comment by tnix100** [comment]
Completed as of 2 days ago
