### ISSUE TITLE
[cl4 | latest commit] return_deleted=False not checked for None before using possible object.

### ISSUE THREAD

**Issue by showierdata9978** [meower-media-co/Meower-Server#165]
## Expected behavior
404 if it does not exist

## Current behavior
500 if it does not exist

## Possible solution
check if the thing is None. if so, raise 404. otherwise continue

## Steps to reproduce
Create an account
Delete that account

block that user on another account

## Did I read the instructions before making this bug report?

**I have HAVE read the instructions.**

## Other

Just looked at the commit.

**Comment by tnix100** [comment]
What object exactly?

**Comment by showierdata9978** [comment]
Anywhere return_deleted=false
