### ISSUE TITLE
[cl4 | newest ] CORS Blocks all headers

### ISSUE THREAD

**Issue by showierdata9978** [meower-media-co/Meower-Server#166]
## Expected behavior
Server sends allowed headers header with `Content-Type` and `Authorization` allowed

![image](https://user-images.githubusercontent.com/68120127/221368845-a13614a4-dd0c-4337-9a45-4030c3701d6a.png)
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSMissingAllowHeaderFromPreflight

## Current behavior

![image](https://user-images.githubusercontent.com/68120127/221368845-a13614a4-dd0c-4337-9a45-4030c3701d6a.png)
![image](https://user-images.githubusercontent.com/68120127/221368958-7b4ddcea-7393-446f-9307-e072f2789275.png)

## Possible solution

Server sends allowed headers header with `Content-Type` and `Authorization` allowed

## Steps to reproduce

on ff
- Auth with API
- Send ANY reqest that needs the `Authorization` header

## Platform info

**Meower Server**
- Python: 3.10
- MongoDB: 6.2.0
- Redis: Redis 5.0.14 for Windows
- Meower Server Version + Build Date: 

**Desktop/Server**
 - OS: Windows
 - Version:  10
 - RAM:8GB
 - Storage: 1TB
 - CPU Architecture: x86_64
 
## Did I read the instructions before making this bug report?

**I have HAVE read the instructions.**

**Comment by MikeDev101** [comment]
For development usage, please use a REST debugging client that does not needs CORS. Try something like: https://github.com/chao/RESTClient

**Comment by showierdata9978** [comment]
> For development, please use a REST debugging client that does not need CORS. Try something like: https://github.com/chao/RESTClient

Can't, was working on kit

**Comment by MikeDev101** [comment]
Suggestion: https://addons.mozilla.org/en-US/firefox/addon/cors-everywhere/

**Comment by showierdata9978** [comment]
I ended up using that Mike

**Comment by tnix100** [comment]
Closing as this seems to be fixed in the production server and CL4 is no longer planned.
