### ISSUE TITLE
[main | latest] Memory leak in rate limiter

### ISSUE THREAD

**Issue by MikeDev101** [meower-media-co/Meower-Server#173]
![image](https://user-images.githubusercontent.com/12957745/226510062-a0c6d67c-8ee6-42a0-8721-a0adf0439c3a.png)
> looks like a memory leak in the meower server or someone is packet spamming

![image](https://user-images.githubusercontent.com/12957745/226510082-095eb6be-64e9-4605-a3f9-5662795056b2.png)
> I noticed yesterday we have a memory leak with the ratelimit system, so yeah that's fun

Will we likely ever fix it? probably not.

**Comment by showierdata9978** [comment]
taking :p hopefully fix it within the week

**Comment by tnix100** [comment]
This has been fixed by using Redis for ratelimit buckets.
