### ISSUE TITLE
[Moderation] HWID BANS

### ISSUE THREAD

**Issue by Bloctans** [meower-media-co/Meower-Server#176]
**Is your feature request related to a problem? Please describe.**
Hardware ID Bans

Ip bans dont really work, and IPHUB doesnt have every VPN IP

**Describe the solution you'd like**
https://www.youtube.com/watch?v=SgkgsgaBBCA&t=350s

This could help with making the system, but requiring more access to the computer.
read that chapter of that video for most of the info needed

Roblox also has a system like this. (Roblox game not angry annoying roblox kid)

**Comment by CST1229** [comment]
i don't think websites have access to the hardware id, and it can probably be bypassed

**Comment by Bloctans** [comment]
> i don't think websites have access to the hardware id, and it can probably be bypassed

yeah but its not as simple as getting a vpn

**Comment by williamhorning** [comment]
This isn't possible at all as many of our clients are web-based and don't have access to information like that. Also that could easily by faked so there's not really a reason to add this.
