### ISSUE TITLE
[main | latest] Remove CL3 payload size limits

### ISSUE THREAD

**Issue by MikeDev101** [meower-media-co/Meower-Server#177]
^

![image](https://user-images.githubusercontent.com/12957745/227043911-61ea5306-b7bc-495c-972e-36413ff2219e.png)

**Comment by showierdata9978** [comment]
Yeah, I relised that, and wanted to abuse it lol

**Comment by mdwalters** [comment]
SHOWIER HOW COULD YOU

**Comment by MikeDev101** [comment]
so depending upon the size of clients, we have a undefined hard limit of users

**Comment by mdwalters** [comment]
ok

**Comment by MikeDev101** [comment]
Yet to be deployed.

**Comment by tnix100** [comment]
Fixed as of https://github.com/meower-media-co/Meower-Server/commit/2a6bd2372f534638e5ffa865d6944fd90a4822f6.
