### ISSUE TITLE
[develop, main | Latest] Add "is_legacy_pfp" boolean to /users/<username>

### ISSUE THREAD

**Issue by MikeDev101** [meower-media-co/Meower-Server#187]
^

All variants of the server should report a boolean "is_legacy_pfp" to tell clients a user's profile icon is a legacy /static/pfp/<pfp_icon>.svg icon. 

This is to keep some degree of compatibility between clients and server versions when user PFP uploads are possible.

**Comment by JoshAtticus** [comment]
I assume this can be closed since avatars and pfps currently coexist, correct me if I'm wrong

**Comment by tnix100** [comment]
Yeah this can be closed.
