### ISSUE TITLE
[CL4 port, CL3, CL3.5 | Latest] Moderation audit log

### ISSUE THREAD

**Issue by theotherhades** [meower-media-co/Meower-Server#190]
**Is your feature request related to a problem? Please describe.**
Yes, recently there has been a number of inappropriate inbox messages sent to certain users by moderators. Under the current system, it is impossible to know who these moderators were.

**Describe the solution you'd like**
An audit log detailing all moderator actions, including information such as the time of the action and the moderator responsible, as well as details of the action itself.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by MikeDev101** [comment]
Agreed. Only MeowyMod has an audit log, having native support would be beneficial.

**Comment by showierdata9978** [comment]
Easy to add to current server Too

**Comment by theotherhades** [comment]
> Easy to add to current server Too

Oh yeah definitely.

**Comment by tnix100** [comment]
This is the reason why I started CL3 rewritten, to add an audit log lmao.

The branch was originally named "tnix-audit-log".

Anyway, audit log is implemented in cl3 rewritten which will hopefully be released soon.

**Comment by tnix100** [comment]
This now exists in 1.8 server.
