### ISSUE TITLE
[develop, main, cl4 | latest] Move chat filter to frontend

### ISSUE THREAD

**Issue by theotherhades** [meower-media-co/Meower-Server#196]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Move the chat filter from the backend to the frontend and store posts as they are written. That way older users who are ok with seeing profanity (such as myself) may opt out of the filter in some way. Not sure how exactly an opt-out would be implemented yet though.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by showierdata9978** [comment]
cl3.5 (or cl4) feature

**Comment by showierdata9978** [comment]
also we already store this data in posts

**Comment by theotherhades** [comment]
Oh lmao I didn't realize `unfiltered_p` existed. Closing.
