### ISSUE TITLE
[main | latest] Add support for message pinning in chats

### ISSUE THREAD

**Issue by MikeDev101** [meower-media-co/Meower-Server#227]
**Describe the solution you'd like**
Server needs to implement new storage fields for message pins.

**Additional context**
![image](https://github.com/meower-media-co/Meower-Server/assets/12957745/d828dc58-e9f4-4003-8623-dc46a62ca60b)

**Comment by showierdata9978** [comment]
GET /chat/<id: str/pins
db.posts.add_index("pinned")
db.posts.find_many({"post_origin": chat_id, "pinned": True})

(pseudo code)
