### ISSUE TITLE
Production Meower server seems to use the default (unsecured) trust key

### ISSUE THREAD

**Issue by Rix565** [meower-media-co/Meower-Server#23]
When I was trying to get my own Meower Server to work on the Meower Client, I noticed that I could just login onto the normal server (using a development client) without any issues.

That's a problem!

Because I literally had an access to the secret moderation panel (through idk if it worked or not), and I had an access to everything! Creating posts, changing settings ETC....

That could lead to custom clients be able to connect to the Meower server.

Change the trust key ASAP!!

**Comment by wgyt** [comment]
this is intentional, the key is meant to be meower
