### ISSUE TITLE
[main| 1.8.2] Unable to delete accounts 

### ISSUE THREAD

**Issue by showierdata9978** [meower-media-co/Meower-Server#230]
## Expected behavior

The account gets deleted 

## Current behavior

The sever returns a internal error 

## Platform info
Dont know their platform

## Other

> top10wiigames
> February 26, 2024 at 2:47:39 PM
>  
> btw when you try to delete accounts, it gives "Unexpected E:104 | Internal error!"

**Comment by tnix100** [comment]
This is now fixed.
