### ISSUE TITLE
Security policy

### ISSUE THREAD

**Issue by tnix100** [meower-media-co/Meower-Server#43]
I think we should make a security policy for the main repositories (most importantly server). Right now GitHub just returns the whole `security.py` file as the security policy, which I honeslty find kinda funny.
![image](https://user-images.githubusercontent.com/61485190/164212522-cc963ffd-7751-4720-b0ac-19d860971dbb.png)

**Comment by MikeDev101** [comment]
lol.

**Comment by ShowierData9978-Alt** [comment]
what you could do is move `security.py`, and stuff like that into  a new dir called `src\` 

then create file called security with ur policy in it

**Comment by tnix100** [comment]
> what you could do is move `security.py`, and stuff like that into a new dir called `src\`
> 
> then create file called security with ur policy in it

Oh we can set which file can be our security policy, we just need to make a security policy.

**Comment by theotherhades** [comment]
I can write one if you want

**Comment by tnix100** [comment]
> I can write one if you want

Sure, that would be appreciated

**Comment by MikeDev101** [comment]
Fixed with https://github.com/meower-media-co/Meower-Server/commit/b2cbcc48322fcb5538e6f6503a0f8674c016dfea, closing.

**Comment by theotherhades** [comment]
hehe oops i forgor
