### ISSUE TITLE
[cl4 | main] Rewrite CL3 codebase for backward compatibility

### ISSUE THREAD

**Issue by tnix100** [meower-media-co/Meower-Server#54]

**Comment by MikeDev101** [comment]
Re-labeling and setting priority. Last time I checked this was already in the works.

**Comment by tnix100** [comment]
Logging in and home functionality works, need to finish account config, inbox, and group chats.

**Comment by tnix100** [comment]
Closing as CL4 is no longer planned and we'll most likely just keep the legacy servers turned on and not worry about re-implementing them in a newer system when the time comes.
