### ISSUE TITLE
How to open .py files without crashing

### ISSUE THREAD

**Issue by Josiah76** [meower-media-co/Meower-Server#96]
Hello, i am making an (small) update to the servers but the py files not loading

**Comment by Bloctans** [comment]
Hello, Josiah76, Can you tell us the errors that are occurring when attempting to open the files?

**Comment by mdwalters** [comment]
might be because you didn't start mongodb first

**Comment by Josiah76** [comment]
modules not loading

**Comment by Bloctans** [comment]
> modules not loading

??????

**Comment by mdwalters** [comment]
Try `pip3 install -r requirements.txt`

**Comment by theotherhades** [comment]
Can you give us more context? Like steps to reproduce, what exactly happens (are there any errors?), etc.

**Comment by mdwalters** [comment]
try using
```
pip3 install -r requirements.txt
```

**Comment by Josiah76** [comment]
It still doesn't work
