### ISSUE TITLE
[cl4 | latest] Upgrade to CL4 protocol

### ISSUE THREAD

**Issue by MikeDev101** [meower-media-co/Meower-Server#98]
Since Beta 6 is not yet ready, the current Beta 5.x server's CL implementation will be upgraded to use Cloudlink 4.

**Comment by mdwalters** [comment]
> Since Beta 6 is not yet ready, the current Beta 5.x server's CL implementation will be upgraded to use Cloudlink 4.

Yay!

**Comment by MikeDev101** [comment]
https://github.com/meower-media-co/Meower-Server/tree/main-cl4-port

**Comment by showierdata9978** [comment]
MeowerBot,py Port is on its way! https://github.com/MeowerBots/MeowerBot.py/tree/cl4

**Comment by mdwalters** [comment]
yay

**Comment by showierdata9978** [comment]
oh, btw your meower API lib is being replaced now too lol (i rewrote it in a async class)

**Comment by mdwalters** [comment]
ok

**Comment by MikeDev101** [comment]
CL4 Optimized was released, development on the CL4 will now resume https://github.com/MikeDev101/cloudlink/commit/e8d3fc400f85b7b4b6057575cfdb4649a7e0e601

**Comment by JoshAtticus** [comment]
Should be closed due to rewrite @MikeDev101

**Comment by tnix100** [comment]
This is no longer planned. We will consider a new WebSocket server in the future but probably won't be CL4.
